### ISSUE TITLE
CSS3 transitions

### ISSUE THREAD

**Issue by niallobrien** [smeevil/reactive-animated-list#1]
Would CSS3 transitions not be a better option instead of relying on js libs?

**Comment by smeevil** [comment]
Actually there are a lot of debates on this indeed. Most of them seem to point out that in the end js might often be faster then hardware accelerated css3 transitions. jQuery is quite slow though, but GSAP or Velocity.js are really fast. Next to that when you want to run multiple transitions at once on the same object , that's (as far as i know) not possible with css transitions.

That said, I might build in plain css transition support as well :)

Some articles that might interest you : 

http://css-tricks.com/myth-busting-css-animations-vs-javascript/
http://davidwalsh.name/css-js-animation
https://developers.google.com/web/fundamentals/look-and-feel/animations/css-vs-javascript?hl=en
